logPath: ""

TokenUrl: "https://safety.yjgl.sz.gov.cn/ytsafe/tooken/tooken.shtml"
RandCodeUrl: "https://safety.yjgl.sz.gov.cn/ytsafe/rand/randCode.shtml"
RandCodeImg: "./randCode.png"
LoginUrl: "https://safety.yjgl.sz.gov.cn/ytsafe/login/login.shtml"

#查询自查自报列表
QueryEntpTypeUrl: "https://safety.yjgl.sz.gov.cn/ytsafe/schInspectListDocEntp/queryEntpType.shtml"

#某个列表下面的所有目录
QueryCheckItemUrl: "https://safety.yjgl.sz.gov.cn/ytsafe/schInspectListDocEntp/queryCheckItem.shtml"

#某个目录下面的目录id对应的章节
QueryCheckItemIDUrl: "https://safety.yjgl.sz.gov.cn/ytsafe/schInspectListDocEntp/queryCheckItemID.shtml"

#查询某个自查项目的隐患内容
QueryCheckInspectUrl: "https://safety.yjgl.sz.gov.cn/ytsafe/selfCheckInspectNegativeList/queryCheckInspect.shtml"

#上报某个自查项目
SaveOrUpdateUrl : "https://safety.yjgl.sz.gov.cn/ytsafe/schNoTrouble/saveOrUpdate.shtml"

#开始上报
ReportUrl: "https://safety.yjgl.sz.gov.cn/ytsafe/schMain/report.shtml"


ListenAddr: ":1234"
WebToken: "sealingp"

User: '深圳市凤慧时装制品有限公司'
Pass: 'ABC8888a'
